### ISSUE TITLE
엑셀VBA 컴파일 오류입니다. 이 프로젝트의 코드를 업데이트해야 64비트 시스템에서 사용할 수 있습니다.

### ISSUE THREAD

**Issue by parkbyunggyu** [parkbyunggyu/pbg_install#2]
![image](https://user-images.githubusercontent.com/44792125/90481082-21eb2e80-e16c-11ea-8291-c049269a9b0f.png)
안녕하세요
portgresql 을 처음 접해봐서
공부차원데서 접근 중인데
vba 엑셀 2016을 사용중에 있습니다.
첨부한 사진 처럼 계속 에러가 발생을 해서 문의를 남겨봅니다.
혹시 code 를 어떻게 수정하면 될까요?
초보적인 질문입니다.
이런 엄청난 프로그램을 만들어주셔어 감사합니다.

_Originally posted by @aceman01 in https://github.com/parkbyunggyu/pbg_install/issues/1#issuecomment-675296874_

**Comment by parkbyunggyu** [comment]
> ![image](https://user-images.githubusercontent.com/44792125/90481082-21eb2e80-e16c-11ea-8291-c049269a9b0f.png)
> 안녕하세요
> portgresql 을 처음 접해봐서
> 공부차원데서 접근 중인데
> vba 엑셀 2016을 사용중에 있습니다.
> 첨부한 사진 처럼 계속 에러가 발생을 해서 문의를 남겨봅니다.
> 혹시 code 를 어떻게 수정하면 될까요?
> 초보적인 질문입니다.
> 이런 엄청난 프로그램을 만들어주셔어 감사합니다.
> 
> _Originally posted by @aceman01 in [#1 (comment)](https://github.com/parkbyunggyu/pbg_install/issues/1#issuecomment-675296874)_

안녕하세요 해당 이슈는 저도 처음보았네요.. 구글링해 확인해보니
에러가 난 빨간 line의 코드에서
Prinvate Declear Sub ... 요부분을
Prinvate Declear Ptrsafe Sub ... 요렇게 바꾼다면 수행이 된다하네요.

현재 제가 테스트를 해볼수 있는 환경이 되지 않아 당장에는 이렇게
테스트를 해보지 못하고 말씀드렸지만, 위에 전달드린 워크로드 방법대로
수행해보신다음 안된다면, 한번더 회신을 부탁드리겠습니다.

이런 조잡한 프로그램을 사용해주셔서 감사합니다 ㅠㅠㅋㅋ
혹시나 마음에 드셨다면,.. github 맨위 우측 메뉴에 보이는 star 하나만 찍어주시길 부탁드릴께용 ㅠㅠㅋㅋ 감사합니다.

**Comment by aceman01** [comment]
알려주신대로 수행하니 해결되었습니다.

답변 감사합니다.

행복한 하루 보내세요.

감사합니다.

star 꾸욱~~~

**Comment by parkbyunggyu** [comment]
> 알려주신대로 수행하니 해결되었습니다.
> 
> 답변 감사합니다.
> 
> 행복한 하루 보내세요.
> 
> 감사합니다.
> 
> star 꾸욱~~~

네네 감사합니다.  나중에 생각나시면 pbg_replication도 사용해보세요 ... 리눅스7에서는 돌아가는데..
리눅스6에서는 돌아가지는 않습니당...
